## Практическое задание

<ol>
    <li>Попробуйте обучить нейронную сеть на Keras с другими параметрами. 
        Опишите в комментарии к уроку - какой результата вы добились от нейросети? Что помогло вам улучшить ее точность?</li>
    <li>Поработайте с документацией Keras.</li>
</ol>

### Исходный Код

In [1]:
# The full neural network code!
###############################
import numpy as np
import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

# Build the model.
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

# Evaluate the model.
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

# Save the model to disk.
model.save_weights('model.h5')

# Load the model from disk later using:
# model.load_weights('model.h5')

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

Using TensorFlow backend.


Epoch 1/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.3617 - accuracy: 0.8914
Epoch 2/5
60000/60000 [==============================] - 4s 71us/step - loss: 0.1857 - accuracy: 0.9434
Epoch 3/5
60000/60000 [==============================] - 5s 90us/step - loss: 0.1459 - accuracy: 0.9554
Epoch 4/5
60000/60000 [==============================] - 5s 89us/step - loss: 0.1253 - accuracy: 0.9613
Epoch 5/5
10000/10000 [==============================] - 1s 52us/step
[7 2 1 0 4]
[7 2 1 0 4]


- Увеличим количество batch

In [4]:
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=320,
)
model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

Epoch 1/5
60000/60000 [==============================] - 1s 19us/step - loss: 0.0396 - accuracy: 0.9881
Epoch 2/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.0342 - accuracy: 0.9897
Epoch 3/5
60000/60000 [==============================] - 1s 20us/step - loss: 0.0325 - accuracy: 0.9904
Epoch 4/5
60000/60000 [==============================] - 1s 18us/step - loss: 0.0312 - accuracy: 0.9906
Epoch 5/5
10000/10000 [==============================] - 0s 35us/step
[7 2 1 0 4]


- До количества входных параметров

In [7]:
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=784,
)
model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

Epoch 1/5
60000/60000 [==============================] - 1s 17us/step - loss: 0.0219 - accuracy: 0.9931
Epoch 2/5
60000/60000 [==============================] - 1s 15us/step - loss: 0.0142 - accuracy: 0.9961
Epoch 3/5
60000/60000 [==============================] - 1s 15us/step - loss: 0.0131 - accuracy: 0.9967
Epoch 4/5
60000/60000 [==============================] - 1s 15us/step - loss: 0.0122 - accuracy: 0.9969
Epoch 5/5
10000/10000 [==============================] - 0s 34us/step
[7 2 1 0 4]


- Увеличим количество epochs

In [5]:
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=10,
  batch_size=32,
)
model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

Epoch 1/10
60000/60000 [==============================] - 4s 75us/step - loss: 0.0712 - accuracy: 0.9767
Epoch 2/10
60000/60000 [==============================] - 5s 78us/step - loss: 0.0597 - accuracy: 0.9807
Epoch 3/10
60000/60000 [==============================] - 4s 73us/step - loss: 0.0563 - accuracy: 0.9815
Epoch 4/10
60000/60000 [==============================] - 5s 75us/step - loss: 0.0527 - accuracy: 0.9823
Epoch 5/10
60000/60000 [==============================] - 5s 77us/step - loss: 0.0498 - accuracy: 0.9831
Epoch 6/10
60000/60000 [==============================] - 5s 75us/step - loss: 0.0491 - accuracy: 0.9841
Epoch 7/10
60000/60000 [==============================] - 5s 76us/step - loss: 0.0442 - accuracy: 0.9852
Epoch 8/10
60000/60000 [==============================] - 5s 75us/step - loss: 0.0455 - accuracy: 0.9844
Epoch 9/10
60000/60000 [==============================] - 4s 74us/step - loss: 0.0420 - accuracy: 0.9858
Epoch 10/10
10000/10000 [==============================

- Увелчим количество unit

In [8]:

model = Sequential([
  Dense(128, activation='relu', input_shape=(784,)),
  Dense(128, activation='relu'),
  Dense(10, activation='softmax'),
])

model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]


Epoch 1/5
60000/60000 [==============================] - 5s 85us/step - loss: 0.3148 - accuracy: 0.9037
Epoch 2/5
60000/60000 [==============================] - 5s 82us/step - loss: 0.1551 - accuracy: 0.9530
Epoch 3/5
60000/60000 [==============================] - 5s 84us/step - loss: 0.1164 - accuracy: 0.9638
Epoch 4/5
60000/60000 [==============================] - 5s 83us/step - loss: 0.0979 - accuracy: 0.9692
Epoch 5/5
10000/10000 [==============================] - 0s 34us/step
[7 2 1 0 4]


- поменяем метод активации

In [10]:
model = Sequential([
  Dense(32, activation='hard_sigmoid', input_shape=(784,)),
  Dense(32, activation='hard_sigmoid'),
  Dense(10, activation='softmax'),
])

model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

Epoch 1/5
60000/60000 [==============================] - 4s 67us/step - loss: 0.8013 - accuracy: 0.7939
Epoch 2/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.2945 - accuracy: 0.9164
Epoch 3/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.2275 - accuracy: 0.9330
Epoch 4/5
60000/60000 [==============================] - 4s 64us/step - loss: 0.1937 - accuracy: 0.9420
Epoch 5/5
10000/10000 [==============================] - 0s 31us/step
[7 2 1 0 4]


- увеличим количество слоев

In [11]:
model = Sequential([
  Dense(32, activation='relu', input_shape=(784,)),
  Dense(32, activation='relu'),
  Dense(32, activation='relu'),
  Dense(10, activation='softmax'),
])

model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

model.evaluate(
  test_images,
  to_categorical(test_labels)
)
predictions = model.predict(test_images[:5])
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

Epoch 1/5
60000/60000 [==============================] - 4s 69us/step - loss: 0.4010 - accuracy: 0.8772
Epoch 2/5
60000/60000 [==============================] - 4s 67us/step - loss: 0.2237 - accuracy: 0.9319
Epoch 3/5
60000/60000 [==============================] - 4s 68us/step - loss: 0.1831 - accuracy: 0.9439
Epoch 4/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.1607 - accuracy: 0.9507
Epoch 5/5
10000/10000 [==============================] - 0s 32us/step
[7 2 1 0 4]


### C keros ознакомился, структура понятна, надо подробнее смотреть все аспекты

- Интересная функция нормализация

In [15]:
from keras.utils import normalize
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
# train_images = (train_images / 255) - 0.5
# test_images = (test_images / 255) - 0.5
train_images = normalize(train_images, axis=-1, order=2)
test_images = normalize(test_images, axis=-1, order=2)


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [ ]:
- Интересный слои шумы, чтобы модель не переобучалась, добавлять их во время обучения